import mongoose from 'mongoose';
import Investment from '../models/Investment.js';
import RoiHistory from '../models/RoiHistory.js';
import User from '../models/User.js';
import { distributeLevelIncome } from './referralService.js';


const toUtcMidnight = (date = new Date()) => {
  const d = new Date(date);
  d.setUTCHours(0, 0, 0, 0);
  return d;
};

export const processInvestmentRoi = async (investment, processDate = new Date()) => {
  const normalizedDate = toUtcMidnight(processDate);
  const roiAmount = Number(
    ((investment.investmentAmount * investment.dailyRoiPercentage) / 100).toFixed(2)
  );

  const session = await mongoose.startSession();
  let credited = false;

  try {
    await session.withTransaction(async () => {
      
      let historyDoc;
      try {
        const created = await RoiHistory.create(
          [
            {
              user: investment.user,
              investment: investment._id,
              roiAmount,
              date: normalizedDate,
              status: 'Credited',
            },
          ],
          { session }
        );
        historyDoc = created[0];
      } catch (err) {
        if (err.code === 11000) {
          // Already processed for this date - safe no-op.
          credited = false;
          return;
        }
        throw err;
      }

      // Step 2: credit the user's wallet and ROI totals
      await User.findByIdAndUpdate(
        investment.user,
        {
          $inc: {
            walletBalance: roiAmount,
            totalRoiEarned: roiAmount,
          },
        },
        { session }
      );

      // Step 3: mark the investment as processed for this date
      await Investment.findByIdAndUpdate(
        investment._id,
        { lastRoiProcessedAt: normalizedDate },
        { session }
      );

      credited = true;

      // Step 4: distribute level/referral income generated by this ROI
      if (historyDoc) {
        await distributeLevelIncome({
          sourceUser: investment.user,
          sourceInvestment: investment._id,
          baseAmount: roiAmount,
          date: normalizedDate,
          session,
        });
      }
    });
  } finally {
    await session.endSession();
  }

  return { credited, amount: credited ? roiAmount : 0 };
};


export const processDailyRoiForAllInvestments = async (processDate = new Date()) => {
  const now = processDate;
  const stats = { processed: 0, credited: 0, skipped: 0, completed: 0 };

  // Auto-complete investments whose term has ended
  const expired = await Investment.updateMany(
    { status: 'Active', endDate: { $lte: now } },
    { $set: { status: 'Completed' } }
  );
  stats.completed = expired.modifiedCount || 0;

 
  const cursor = Investment.find({
    status: 'Active',
    startDate: { $lte: now },
    endDate: { $gt: now },
  }).cursor();

  // eslint-disable-next-line no-restricted-syntax
  for await (const investment of cursor) {
    stats.processed += 1;
    // eslint-disable-next-line no-await-in-loop
    const result = await processInvestmentRoi(investment, now);
    if (result.credited) {
      stats.credited += 1;
    } else {
      stats.skipped += 1;
    }
  }

  return stats;
};

export { toUtcMidnight };
